# using needs here, each jobs depends on each other. This is my manually excecuting cicd pipeline.
name: cicd  #anme of the workflow
on:
 workflow_dispatch:    # manual run pipeline whienever user needs
  inputs:
    environmet:
     description: This is a env, where you wnat to run your worflow
     default: 'prod'
     type: choice
     required: true
     options:
       - dev
       - prod
       - staging

jobs:
  code:     #job1
   runs-on: ubuntu-latest
   steps:
     - name: checkout the code
       run: echo "code clone form github"

  build:   #job2
   needs: code
   runs-on: ubuntu-latest
   steps:
     - name: build docker contanier
       run: echo "docker container buils"

  test:   #job3
   needs: build
   runs-on: ubuntu-latest
   steps:
     - name: test the container
       run: echo "test the contaner is running"

  deploy:   #job4
   if: inputs.environment == 'dev'
   needs: test
   runs-on: ubuntu-latest
   steps:
     - name: deploy the application
       run:  echo "application deplyed by docker compose"
