#This is the name of the workflow
name: Hello
on:
 push:
   branches: main
   paths:
     - '**.yml'
#Now adding the JOb inside the workflow
jobs:
# Below is the name of the job  
  job1greet:
   runs-on: ubuntu-latest  # this is the server, every job needs a server
   steps:
     - name: say hi to the user
       run: echo "heloo Jayant"
     - name: sat hi to username
       run: echo "hello $USER"

     - run: whoami

     - run: pwd
     - run: hostname
     - run: ls -la
    
  job2details:
     runs-on: ubuntu-latest
     steps:
      - name: tell me the verion of python and docker
        run: docker --version && python --version
  
  

  
   
